@startuml
left to right direction

entity Account {
  +id : Long <<PK>>
  --
  name : String <<NOT NULL>>
}


' amountは必ず正の整数（Validationで制御）
entity Expense {
  +id : Long <<PK>>
  --
  amount : Integer <<NOT NULL>>
  type : ExpenseType <<NOT NULL>> 
  date : LocalDate <<NOT NULL>>
  memo : String 
  account : Account <<FK>><<NOT NULL>>
  category : Category <<FK>><<NOT NULL>>
}

note left of Expense
Enum: income / expense
CHECK (amount >= 0)

Enum: 
end note

Account ||--o{ Expense

@enduml
