@startuml
left to right direction




entity User {
  +id : Long <<PK>>
  --
  name : String <<NOT NULL>>
  email : String <<UNIQUE>><<NOT NULL>>
  password : String <<NOT NULL>>
}

entity Category {
  +id : Long <<PK>>
  --
  name : String <<NOT NULL>>
  user_id : Long <<FK>><<NOT NULL>>
}

note right of Category
UNIQUE(user_id, name)
end note

' amountは必ず正の整数（Validationで制御）
entity Expense {
  +id : Long <<PK>>
  --
  amount : Integer <<NOT NULL>>
  type : ExpenseType <<NOT NULL>> 
  date : LocalDate <<NOT NULL>>
  memo : String 
  user_id : Long <<FK>><<NOT NULL>>
  category_id : Long <<FK>><<NOT NULL>>
}

note left of Expense
Enum: income / expense
CHECK (amount >= 0)
end note

User ||--o{ Category
User ||--o{ Expense
Category ||--o{ Expense

@enduml
